### ISSUE TITLE
Monk tree icons upside-down

### ISSUE THREAD

**Issue by Koozboi** [ianlamb/stolen-realm-planner#1]
Hey friend ! Thanks for the planner :) as indicated in the title, some icons are upside-down in the Monk tree :

actives

-incapacitate
-pain suppression
-meditation
-dashing strikes

passives

-momentum
-contemplation
-masochism
-combo breaker
-crash and flow

**Comment by DanDuhon** [comment]
This is fixed!

**Comment by ianlamb** [comment]
Thanks for reporting and for the fix!
