### ISSUE TITLE
Skills not displaying weapon type dependencies

### ISSUE THREAD

**Issue by Shamrock63** [ianlamb/stolen-realm-planner#5]
Certain skills which require specific weapon types to be equipped to be used do not currently display that requirement, leading to ambiguity in what can be used in melee vs ranged weapon builds.

**Comment by ianlamb** [comment]
That's a good feature suggestion, I can try to work on this when I have some free time.

**Comment by ianlamb** [comment]
Hi, I've added the required weapon type labels. Please have a look and re-open this issue if I missed any 😄
