### ISSUE TITLE
Bad Bloom 0 CD

### ISSUE THREAD

**Issue by Smite-Sion** [ianlamb/stolen-realm-planner#8]
I am working on a character file reader and I am using the json file for the tree (src/data/skills.json) and I noticed bad bloom has "cooldown": ""

I now it is really small, just something I noticed, sorry for being annoying xD

**Comment by ianlamb** [comment]
Not annoying at all, thanks for reporting! What should the value be?

Also I'd be curious to see your work on the file reader if you care to share it, I was going to start working on one myself but other things started taking priority in life.

**Comment by Smite-Sion** [comment]
The value should be 2

For the character reader I started on it yesterday, so it is pretty much in the early works.
I am just a simple Java dev, so I will be making it in Java and you just run it as an executable, I have no plans on deploying it on the web as I have almost 0 experience with that.

For the character json it self, almost everything in their is in ID's written. But you can reverse engineer what the ID's are when changing things around in the game, it just takes quite a bit of time to do and requires you to have all the items and fortunes etc.

When the reading is complete, I hope to create an interface so you can easily modify the character or to create new characters. Like creating a character at a specific level and with what fortunes & items.

The only thing is, I am not sure when I am done with it if I should share it publicly. As it can remove quite a bit of fun elements from a game, but it will definitely help with us finding bugs for the devs to fix at least.

**Comment by ianlamb** [comment]
Yeah the reverse engineering part is what I don't have time to do heh. If you ever do want to share your work publicly let me know, but either way cool project to work on! At some point I was hoping to add more of a character builder aspect where you could import a save file and play around with stats and gear, but it just seemed like a lot of work 😅

I've updated The Bad Bloom cooldown, thanks again! Don't hesitate to report any other issues :)
